Repository hackclub/jams, pull requests merged in 2023-07, with the labels that each got.

#9 CRUD app with Firebase
  jams/data-web-app.md
Labels: ready to merge

#24 Multi-part jam proposal for Unity whack-a-mole game
  jams/close_call.md
Labels: question

#23 WebGL Shaders: Drawing fractals with JavaScript
  jams/fractals.md
Labels: ready to merge

#26 3D Modeling Workshop Proposal
  jams/3D_Modeling_Web_Based.md
Labels: ready to merge

#33 Creating interactive 3D worlds on the web
  jams/creating-3d-worlds-web
Labels: ready to merge

#28 Snow Globe!
  jams/Snowglobe.md
Labels: enhancement, in progress

#4 Create AI powered Trip Itinerary
  jams/itinerary.md
Labels: ready to merge

#39 Create_Build_Your_Own_Adventure.md
  jams/Build_Your_Own_Adventure.md
Labels: good first proposal, in progress

#31 Propose Storefront Design project
  jams/Storefront_Design.md
Labels: sarthak's review needed
